stages:
  - prepare
  - build

variables:
  ORIGINAL_DIR: "%CI_PROJECT_DIR%"
  OUTPUT_DIR: "./output"
  APP_PROJECT: "./mark_of_idle/mark_of_idle.csproj"
  SETUP_V1_PROJECT: "./setup_v1/setup_v1.csproj"
  UNINSTALL_PROJECT: "./uninstall/uninstall.csproj"

image: mcr.microsoft.com/dotnet/sdk:latest

prepare:
  stage: prepare
  script:
    - echo "Project Current Directory"
    - echo $env:CI_PROJECT_DIR
    - echo "Listing files:"
    - dir  # On Windows, list files in the current directory
    - echo "Running prepare.bat..."
    - ./infra/prepare.bat
  tags:
    - windows


build:
  stage: build
  script:
    - echo "Project Current Directory"
    - echo $env:CI_PROJECT_DIR
    - echo "Listing files:"
    - echo "Running build.bat..."
    - ./infra/build.bat
  tags:
    - windows


  