stages:
  - deployable
  - cleanup

variables:
  ORIGINAL_DIR: "%CI_PROJECT_DIR%"
  OUTPUT_DIR: "./output"
  APP_PROJECT: "./mark_of_idle/mark_of_idle.csproj"
  SETUP_V1_PROJECT: "./setup_v1/setup_v1.csproj"
  UNINSTALL_PROJECT: "./uninstall/uninstall.csproj"

image: mcr.microsoft.com/dotnet/sdk:latest

deployable:
  stage: deployable
  script:
    - echo "Project Current Directory"
    - echo $env:CI_PROJECT_DIR
    - echo "Listing files:"
    - dir  # On Windows, list files in the current directory
    - echo "Running deployable.bat..."
    - ./publish.bat
  only:
    - main
  tags:
    - windows


# Job to revert changes if the pipeline fails
revert_changes:
  stage: cleanup
  script:
    - |
      if [ "$CI_JOB_STATUS" == "failed" ]; then
        echo "Pipeline failed, reverting changes..."
        git fetch origin
        git reset --hard HEAD~1  # Reverts the last commit
        git push origin HEAD:refs/heads/$CI_COMMIT_REF_NAME --force  # Pushes the revert back to the branch
      else
        echo "Pipeline succeeded, skipping revert."
      fi
  when: on_failure  # Only runs if a previous job failed
  only:
    - main 
    



  