stages:
  - prepare
  - build

variables:
  ORIGINAL_DIR: "%CI_PROJECT_DIR%"
  OUTPUT_DIR: "./output"
  APP_PROJECT: "./mark_of_idle/mark_of_idle.csproj"
  SETUP_V1_PROJECT: "./setup_v1/setup_v1.csproj"
  UNINSTALL_PROJECT: "./uninstall/uninstall.csproj"

image: mcr.microsoft.com/dotnet/sdk:latest

prepare:
  stage: prepare
  script:
    - echo "Running prepare.sh..."  # Change from prepare.bat to prepare.sh
    - echo "Current Directory $CI_PROJECT_DIR"
    - echo "Listing files:"
    - ls -l  # List files in the current directory (Linux equivalent of dir)
    - echo "Running prepare.sh..."
    - chmod +x ./infra/prepare.sh  # Make sure the script is executable
    - ./infra/prepare.sh  # Run the Linux shell script (prepare.sh instead of prepare.bat)
  tags:
    - linux  # Ensure you have a runner with the appropriate tag for Linux


build:
  stage: build
  script:
    - echo "Running build.sh..." 
    - echo "Current Directory $CI_PROJECT_DIR"
    - echo "Listing files:"
    - ls -l 
    - echo "Running build.sh..."
    - chmod +x ./infra/build.sh  
    - ./infra/build.sh  
  tags:
    - linux  


  