stages:
  - prepare
  - build

variables:
  ORIGINAL_DIR: "%CI_PROJECT_DIR%"
  OUTPUT_DIR: ".\output"
  APP_PROJECT: ".\mark_of_idle\mark_of_idle.csproj"
  SETUP_V1_PROJECT: ".\setup_v1\setup_v1.csproj"
  UNINSTALL_PROJECT: ".\uninstall\uninstall.csproj"

image: mcr.microsoft.com/dotnet/sdk:latest

prepare:
  stage: prepare
  script:
    - echo Running prepare.bat...
    - echo %CI_PROJECT_DIR%
    - echo "Listing files:"
    - dir  # CMD equivalent to list files
    - echo Running prepare.bat...
    - call .\infra\prepare.bat  # Windows call to execute batch file
  tags:
    - windows

build:
  stage: build
  script:
    - echo Running build.bat...
    - call .\infra\build.bat  # Windows call to execute batch file
  tags:
    - windows
