stages:
  - deployable
  - cleanup

variables:
  PROJECT_PATH: "$CI_PROJECT_PATH"
  GIT_BRANCH: "$CI_COMMIT_REF_NAME"
  ORIGINAL_DIR: "%CI_PROJECT_DIR%"
  OUTPUT_DIR: "./output"
  APP_PROJECT: "./mark_of_idle/mark_of_idle.csproj"
  SETUP_V1_PROJECT: "./setup_v1/setup_v1.csproj"
  UNINSTALL_PROJECT: "./uninstall/uninstall.csproj"

deployable:
  stage: deployable
  script:
    - echo "Project Current Directory"
    - echo $env:CI_PROJECT_DIR
    - echo "Listing files:"
    - dir  # On Windows, list files in the current directory
    - echo "Running deployable.bat..."
    - ./publish.bat
  only:
    - main
  tags:
    - windows


# Job to revert changes if the pipeline fails
revert_changes:
  stage: cleanup
  script:
    - |
      echo "Pipeline failed, reverting changes..."
      git remote set-url origin git@gitlab.com:$PROJECT_PATH.git
      git remote -v
      git fetch origin
      git pull origin $GIT_BRANCH --rebase

      # Reverts the last commit
      git reset --hard HEAD~1

      # Pushes the revert back to the branch
      git push --force origin HEAD:refs/heads/$GIT_BRANCH
  when: on_failure  # Only runs if a previous job failed
  only:
    - main
  tags:
    - windows 
    



  